[target.'cfg(all(target_arch = "arm", target_os = "none"))']
#runner = "probe-rs run --chip nRF52832_xxAA"
#runner = "probe-rs run --chip nRF52833_xxAA"
runner = "probe-rs run --chip nRF54l15"

[build]
target = "thumbv8m.main-none-eabihf"

[env]
DEFMT_LOG = "trouble_host=trace,info"
